tenantName: tenant-a
image:
  repository: ghcr.io/confused-coder1919/outsight-platform-devops-demo/demo-api
  tag: sha-5601734
rollouts:
  enabled: true
analysis:
  enabled: true
  successCondition5xx: result[0] == 0
  failureCondition5xx: result[0] > 0
